
export const menu = [
  {
    id: 1,
    name: 'Double Cheeseburger',
    category: 'sandwich',
    image: 'double_burger.jpeg',
    priceIcon: '$$$',
    price: '$18.99',
    description:  `Two juicy beef patties with lettuce, tomato, onion, american cheese. Served with fries or a side salad.`,
    course: 'main',
    emoji: `🍔`,
  },
  {
    id: 2,
    name: 'American Classic',
    category: 'sandwich',
    image: 'burger-2.jpg',
    priceIcon: '$$',
    price: '$16.99',
    description:  `Tried and true. Juicy beef patty with lettuce, tomato, onion, american cheese. Served with fries or a side salad.`,
    course: 'main',
    emoji: `🍔`,
  },
  {
    id: 3,
    name: 'The Chicken Burger',
    category: 'sandwich',
    image: 'burger-4.jpg',
    priceIcon: '$$',
    price: '$15.99',
    description:  `Chicken breast, caramelized onions, pickles, and our secret sauce, on a toasted sesame bun`,
    course: 'main',
    emoji: `🍔`,
  },
  {
    id: 4,
    name: 'Morning Burger',
    category: 'sandwich',
    image: 'burger-3.jpg',
    priceIcon: '$$$',
    price: '$17.99',
    description:  `Juicy beef patty with ham, bacon, egg, and american cheese on a toasted white bun `,
    course: 'main',
    emoji: `🍔`,
  },
  {
    id: 5,
    name: 'Feta & Arugala Pizza',
    category: 'pizza',
    image: 'pizza-2.jpg',
    priceIcon: '$$',
    price: '$15.99',
    description:  `Fresh arugala leaves over a thin crust pizza. Topped with feta, and mushrooms.`,
    course: 'main',
    emoji: `🍕`,
  },
  {
    id: 6,
    name: 'Supreme Pizza',
    category: 'pizza',
    image: 'pizza-3.jpg',
    priceIcon: '$$$',
    price: '$15.99',
    description:  `Italian sausage, pepperoni, banana peppers, mushrooms, black olives, onions, mozzarella and spicy red sauce. Limited substitutions.`,
    course: 'main',
    emoji: `🍕`,
  },
  {
    id: 7,
    name: 'BBQ Chicken Pizza',
    category: 'pizza',
    image: 'pizza-4.jpg',
    priceIcon: '$$$',
    price: '$15.99',
    description:  `Our Chef’s signature recipe includes chicken, crumbled cheese, onions, mozzarella, and our classic BBQ sauce.`,
    course: 'main',
    emoji: `🍕`,
  },
  {
    id: 8,
    name: 'Cheese Pizza',
    category: 'pizza',
    image: 'pizza-5.jpg',
    priceIcon: '$',
    price: '$15.99',
    description:  `Mozzarella, parmesan, and our classic red sauce`,
    course: 'main',
    emoji: `🍕`,
  },

  {
    id: 9,
    name: 'Kale Salad',
    category: 'salad',
    image: 'kale_salad.avif',
    priceIcon: '$$',
    price: '$15.99',
    description:  `Chopped kale, tomatoes, red onions, scallions, avocado, crispy tortilla strips, and served with a citrus vinaigrette.`,
    course: 'starter',
    emoji: `🥗`,
  },
  {
    id: 10,
    name: 'Ceasar Salad',
    category: 'salad',
    image: 'ceasar_salad.avif',
    priceIcon: '$',
    price: '$13.99',
    description:  `House Ceasar Salad with crutons, shaved parmesan, tomatoes, cucumbers, and ceasar dressing`,
    course: 'starter',
    emoji: `🥗`,
  },
  {
    id: 11,
    name: 'Loaded Salad',
    category: 'salad',
    image: 'loaded_salad.avif',
    priceIcon: '$$$',
    price: '$14.99',
    description:  `Artisian salad loaded with 5 super foods.`,
    course: 'starter',
    emoji: `🥗`,
  },
  {
    id: 12,
    name: 'Fruit Salad',
    category: 'salad',
    image: 'fruit_salad.avif',
    priceIcon: '$$',
    price: '$16.99',
    description:  `Bananas, Strawberries, Grapes, Pineapple, Mango, Peaches`,
    course: 'starter',
    emoji: `🍇`,
  },
  {
    id: 13,
    name: 'Wings',
    category: 'chicken',
    image: 'chicken_wings.avif',
    priceIcon: '$$',
    price: '$14.99',
    description:  `10 Chicken Wings tossed in one of our 12 sauces or rubs. Boneless or Bone-In`,
    course: 'starter',
    emoji: `🍗`,
  },
  {
    id: 14,
    name: 'Baked Chicken',
    category: 'chicken',
    image: 'baked_chicken.avif',
    priceIcon: '$$$',
    price: '$25.99',
    description:  'Grilled boneless skinless chicken topped with melted provolone, cheddar, and Swiss cheeses, sautéed mushrooms, peppers, and grilled onions. Served with seasonal vegetables. ',
    course: 'main',
    emoji: `🍗`,
  },
  {
    id: 15,
    name: 'Chicken Tenders',
    category: 'chicken',
    image: 'chicken_tenders.avif',
    priceIcon: '$',
    price: '$19.99',
    description:  'Five chicken tenders: Plain, Buffalo, or tossed in choice of wing sauce. Served with choice of dipping sauce.',
    course: 'main',
    emoji: `🍗`,
  },
  {
    id: 16,
    name: 'Chicken Kabob',
    category: 'chicken',
    price: '$23.99',
    description:  `Served with rice, grilled vegetables, salad, pita bread and tzatziki sauce. Choice of regular or brown basmati rice and regular or whole grain pita`,
    course: 'main',
    emoji: `🍗`,
    image: 'chicken_kabob.avif',
    priceIcon: '$$$',
  },
  {
    id: 17,
    name: 'Greek Potatoes',
    priceIcon: '$',
    price: '$8.99',
    description: `Potato wedges lightly fried and served with our zesty garlic sauce`,
    course: 'starter',
    category: '',
    image: 'greek_potatoes.jpeg',
    emoji: `🥔`,
},
{
  id: 18,
  name: 'Shrimp Skewer',
  price: '$9.99',
  description: `Barbeque seasoned shrimp on a skewer`,
  category: '',
  course: 'starter',
  image: 'shrimp.jpeg',
  emoji: `🍤`,
},
{
  id: 19,
  name: 'Pasta Marinara',
  price: '$14.99',
  description: `Your choice of our marinara, arrabbiata or vodka sauce with linguini, fettuccini or penne pasta.`,
  category: 'pasta',
  course: 'main',
  image: 'pasta_marinara.jpg',
  emoji: `🍝`,
},
{
  id: 20,
  name: 'Roasted Turkey BLT',
  price: '$13.99',
  description: `Roasted turkey breast, Applewood smoked bacon, lettuce, tomato and provolone cheese with our chipotle mayo.`,
  category: 'sandwich',
  course: 'main',
  image: 'blt.jpeg',
  emoji: `🥪`,
},
{
  id: 21,
  name: 'Fudge Brownie',
  price: '$4.99',
  description: `Fresh baked brownie`,
  category: '',
  course: 'dessert',
  image: 'brownie.webp',
  emoji: ``,
},
{
  id: 22,
  name: 'Slice of Cake',
  price: '$5.99',
  description: `Chocolate, Vanilla, or Cheesecake`,
  category: '',
  course: 'dessert',
  image: 'cake.jpeg',
  emoji: `🍰`,
},
{
  id: 23,
  name: 'Freshly Baked Cookies',
  price: '$4.99',
  description: `3 Cookies. Your choice of Chocolate Chip, Sugar, and Oatmeal`,
  category: '',
  course: 'dessert',
  image: 'cookies.jpeg',
  emoji: `🍪`,
},
];